# Generated by Django 5.1 on 2024-10-14 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatesModel',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('statename', models.CharField(max_length=50)),
                ('statecode', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'tbl_states',
            },
        ),
    ]
