# Generated by Django 5.1 on 2024-10-14 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Location', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statesmodel',
            name='statecode',
        ),
    ]
