# Generated by Django 5.1 on 2024-10-14 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Location', '0002_remove_statesmodel_statecode'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityModel',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('cityname', models.CharField(max_length=50)),
                ('state_id', models.ForeignKey(db_column='state_id', default=None, on_delete=django.db.models.deletion.CASCADE, to='Location.statesmodel')),
            ],
            options={
                'db_table': 'tbl_city',
            },
        ),
    ]
