# Generated by Django 5.1 on 2024-10-21 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AdminProduct', '0002_productmodel_subcat_id'),
        ('Checkout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemModel',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('qty', models.PositiveIntegerField(default=0)),
                ('price', models.FloatField()),
                ('order_id', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, to='Checkout.ordermodel')),
                ('productId', models.ForeignKey(db_column='productId', on_delete=django.db.models.deletion.CASCADE, to='AdminProduct.productmodel')),
            ],
            options={
                'db_table': 'tbl_item',
            },
        ),
    ]
