# Generated by Django 5.1 on 2024-10-18 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AdminProduct', '0002_productmodel_subcat_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('qty', models.PositiveIntegerField(default=1)),
                ('price', models.FloatField()),
                ('productId', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='AdminProduct.productmodel')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_cart',
            },
        ),
    ]
