# Generated by Django 5.1 on 2024-10-08 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AdminCategory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubcatModel',
            fields=[
                ('subcat_id', models.AutoField(primary_key=True, serialize=False)),
                ('subcategoryName', models.CharField(max_length=50)),
                ('subcategoryImage', models.CharField(max_length=100)),
                ('cat_id', models.ForeignKey(db_column='cat_id', default=None, on_delete=django.db.models.deletion.CASCADE, to='AdminCategory.categorymodel')),
            ],
            options={
                'db_table': 'tbl_subcategory',
            },
        ),
    ]
