# Generated by Django 5.1 on 2024-10-22 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermodel',
            old_name='city',
            new_name='city_id',
        ),
    ]
