# Generated by Django 5.1 on 2024-10-07 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('categoryName', models.CharField(max_length=50)),
                ('categoryImage', models.CharField(default=None, max_length=100)),
            ],
            options={
                'db_table': 'tbl_category',
            },
        ),
    ]
