# Generated by Django 5.1 on 2024-10-10 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('productId', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('descriptions', models.TextField()),
                ('price', models.FloatField()),
                ('sellPrice', models.FloatField()),
                ('image1', models.CharField(default=None, max_length=100)),
                ('image2', models.CharField(default=None, max_length=100)),
                ('image3', models.CharField(default=None, max_length=100)),
                ('videoUrl', models.URLField(blank=True, null=True)),
                ('isActive', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'tbl_product',
            },
        ),
    ]
