# Generated by Django 5.1 on 2024-10-10 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminProduct', '0001_initial'),
        ('Adminsubcategory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='subcat_id',
            field=models.ForeignKey(db_column='subcat_id', default=None, on_delete=django.db.models.deletion.CASCADE, to='Adminsubcategory.subcatmodel'),
        ),
    ]
